# Generated by Django 5.1.2 on 2024-10-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talk',
            new_name='Pizza',
        ),
    ]
